wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1670877820.792595
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      - 71
      - 79
      3:
      - 13
      - 14
      - 23
      4: 3.8.10
      5: 0.13.6
      6: 4.24.0
      8:
      - 5
