wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: huggingface
    huggingface_version: 4.24.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1672775028.235758
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      - 41
      - 49
      - 55
      - 71
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.8.10
      5: 0.13.6
      6: 4.24.0
      8:
      - 5
      - 9
epochs:
  desc: null
  value: 12
gradient_accumulation_steps:
  desc: null
  value: 8
include_summary:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 5.0e-06
num_templates:
  desc: null
  value: 4
output_dir:
  desc: null
  value: ./model
pretrained_model_name_or_path:
  desc: null
  value: CompVis/stable-diffusion-v1-4
scale_lr:
  desc: null
  value: false
seed:
  desc: null
  value: 42
templates:
  desc: null
  value:
  - 'A {} book cover with author {}, book title {} '
  - 'A {} book cover written by author {} with book title {} '
  - A  {} book cover with author name:{}, book title: {}
  - 'A detailed {} book cover with author {} and book title {} '
train_batch_size:
  desc: null
  value: 1
train_text_encoder:
  desc: null
  value: true
train_unet:
  desc: null
  value: false
training_dataset_size:
  desc: null
  value: 6000
weight_decay:
  desc: null
  value: 0.01
